import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface Question {
  question_text: string;
  options: string[];
  correct_answer: number;
  explanation?: string | null;
}

interface QuizPdfDownloadProps {
  title: string;
  questions: Question[];
  score?: number;
  correctAnswers?: number;
  includeAnswers?: boolean;
}

export function QuizPdfDownload({ 
  title, 
  questions, 
  score, 
  correctAnswers,
  includeAnswers = true 
}: QuizPdfDownloadProps) {
  const { toast } = useToast();

  const generatePdfContent = () => {
    const header = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
      line-height: 1.6;
      color: #333;
    }
    .header { 
      text-align: center; 
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 3px solid #6366f1;
    }
    .header h1 { 
      font-size: 28px; 
      color: #1a1a2e;
      margin-bottom: 10px;
    }
    .header .subtitle {
      color: #666;
      font-size: 14px;
    }
    .stats {
      display: flex;
      justify-content: center;
      gap: 30px;
      margin-top: 20px;
    }
    .stat-item {
      text-align: center;
      padding: 10px 20px;
      background: #f5f5ff;
      border-radius: 8px;
    }
    .stat-value {
      font-size: 24px;
      font-weight: bold;
      color: #6366f1;
    }
    .stat-label {
      font-size: 12px;
      color: #666;
    }
    .question {
      margin-bottom: 30px;
      page-break-inside: avoid;
    }
    .question-header {
      display: flex;
      align-items: flex-start;
      gap: 10px;
      margin-bottom: 15px;
    }
    .question-number {
      background: #6366f1;
      color: white;
      width: 30px;
      height: 30px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: bold;
      font-size: 14px;
      flex-shrink: 0;
    }
    .question-text {
      font-weight: 600;
      font-size: 16px;
      color: #1a1a2e;
    }
    .options {
      margin-left: 40px;
    }
    .option {
      padding: 10px 15px;
      margin-bottom: 8px;
      background: #f8f9fa;
      border-radius: 6px;
      border-left: 3px solid transparent;
    }
    .option.correct {
      background: #d4edda;
      border-left-color: #28a745;
    }
    .option-letter {
      font-weight: bold;
      margin-right: 10px;
      color: #6366f1;
    }
    .explanation {
      margin-left: 40px;
      margin-top: 10px;
      padding: 10px 15px;
      background: #fff3cd;
      border-radius: 6px;
      font-size: 13px;
      color: #856404;
    }
    .explanation-label {
      font-weight: bold;
    }
    .answer-key {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 2px solid #ddd;
    }
    .answer-key h2 {
      font-size: 20px;
      margin-bottom: 20px;
      color: #1a1a2e;
    }
    .answer-grid {
      display: grid;
      grid-template-columns: repeat(5, 1fr);
      gap: 10px;
    }
    .answer-item {
      padding: 8px;
      background: #f5f5ff;
      border-radius: 4px;
      text-align: center;
      font-size: 13px;
    }
    .footer {
      margin-top: 40px;
      text-align: center;
      font-size: 12px;
      color: #999;
      padding-top: 20px;
      border-top: 1px solid #eee;
    }
    @media print {
      body { padding: 20px; }
      .question { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>📝 ${title}</h1>
    <p class="subtitle">Generated by Delton Quizz</p>
    ${score !== undefined ? `
    <div class="stats">
      <div class="stat-item">
        <div class="stat-value">${score}</div>
        <div class="stat-label">Score</div>
      </div>
      <div class="stat-item">
        <div class="stat-value">${correctAnswers}/${questions.length}</div>
        <div class="stat-label">Correct</div>
      </div>
      <div class="stat-item">
        <div class="stat-value">${Math.round((correctAnswers || 0) / questions.length * 100)}%</div>
        <div class="stat-label">Accuracy</div>
      </div>
    </div>
    ` : ''}
  </div>
`;

    const questionsHtml = questions.map((q, index) => {
      const optionsHtml = q.options.map((opt, optIndex) => `
        <div class="option ${includeAnswers && optIndex === q.correct_answer ? 'correct' : ''}">
          <span class="option-letter">${String.fromCharCode(65 + optIndex)}.</span>
          ${opt}
        </div>
      `).join('');

      return `
        <div class="question">
          <div class="question-header">
            <div class="question-number">${index + 1}</div>
            <div class="question-text">${q.question_text}</div>
          </div>
          <div class="options">
            ${optionsHtml}
          </div>
          ${includeAnswers && q.explanation ? `
            <div class="explanation">
              <span class="explanation-label">💡 Explanation:</span> ${q.explanation}
            </div>
          ` : ''}
        </div>
      `;
    }).join('');

    const answerKey = includeAnswers ? `
      <div class="answer-key">
        <h2>📋 Answer Key</h2>
        <div class="answer-grid">
          ${questions.map((q, i) => `
            <div class="answer-item">
              <strong>Q${i + 1}:</strong> ${String.fromCharCode(65 + q.correct_answer)}
            </div>
          `).join('')}
        </div>
      </div>
    ` : '';

    const footer = `
  <div class="footer">
    <p>Quiz generated by Delton Quizz • ${new Date().toLocaleDateString()}</p>
  </div>
</body>
</html>
`;

    return header + questionsHtml + answerKey + footer;
  };

  const handleDownload = () => {
    const content = generatePdfContent();
    
    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast({
        title: 'Error',
        description: 'Please allow popups to download the PDF',
        variant: 'destructive'
      });
      return;
    }

    printWindow.document.write(content);
    printWindow.document.close();

    // Wait for content to load, then trigger print
    printWindow.onload = () => {
      printWindow.print();
    };

    toast({
      title: 'PDF Ready',
      description: 'Use the print dialog to save as PDF'
    });
  };

  return (
    <Button variant="outline" onClick={handleDownload} className="gap-2">
      <Download className="w-4 h-4" />
      Download PDF
    </Button>
  );
}
